# Generated by Django 2.2.9 on 2020-01-08 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_dimensions', models.PositiveIntegerField()),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File')),
            ],
        ),
    ]
