# Generated by Django 2.2.9 on 2020-01-15 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_auto_20200115_1010'),
        ('batch', '0003_auto_20200114_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='batch.Project'),
        ),
        migrations.AddField(
            model_name='job',
            name='raw_data',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='datasets.Dataset'),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
