# Generated by Django 2.2.9 on 2020-01-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_job_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('running', 'running'), ('done', 'done'), ('failed', 'failed'), ('collected', 'collected')], default='created', max_length=20),
        ),
    ]
