# Generated by Django 2.2.9 on 2020-01-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_auto_20200117_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='started_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
