# Generated by Django 2.2.9 on 2020-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_auto_20200117_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow',
            field=models.CharField(default='Pixel Classification', max_length=255),
            preserve_default=False,
        ),
    ]
