# Generated by Django 2.2.9 on 2020-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_auto_20200117_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
